### PR TITLE
Add Theme to Format type

### PR DESCRIPTION
**Pull request by webb04**
## What does this change?
Add theme field to Format. Articles can have a pillar theme or a special report theme.

We looked into adding SpecialReport as a "Design Type" but it would conflict with some like Analysis articles.

### CODE REVIEW

**Review by frankie297 — APPROVED** [review]
👍

**Comment by JamieB-gu** [comment]
I've added a few extra reviewers because I think it would be good to get some opinions on this, I hope you don't mind @webb04 😬!

For context, this came out of a discussion @webb04 and I were having about how to mark a piece of content as a "Special Report". Any piece of content marked as "special report" (this happens through a combination of the targeting tool and CAPI's `isSpecialReport` field) has some special styles applied to it that override a lot of the colours ([here](https://www.theguardian.com/news/series/panama-papers) are some examples).

For the rendering platforms (AR, DCR, etc.) we've settled on the idea that the `Format` type, defined in this repo, should encapsulate **all** the information needed to represent the design of a given piece of content. I think this has worked quite well so far, with the notable exception of "special reports", which aren't captured by this `Format` type. We can't use `Design` to represent them, because they can apply to a number of designs, and we can't use `Display` for the same reason. It's possible we could integrate them into `Pillar` in some way, or come up with something new.

Some of the options Jamie and I considered were:

1. Make `SpecialReport` the sixth pillar
2. Create a superset of `Pillar` named `Theme` that would include the pillars _and_ special report (the change made in this PR)
3. Add a fourth field to `Format`, something like `specialReport: boolean;`

**Note:** 1) and 2) are only possible if the pillar is no longer relevant for special report articles, as it makes pillar and the special report status mutually exclusive. If it's valid for an article to be a special report _and_ for it to have a pillar that affects its design, then we hit the same problem as with `Design` and `Display`.

This is a topic the platform teams (apps, dotcom, design system etc.) have discussed before, but not come to a conclusion on as yet... maybe we can sort it out now!

**Comment by SiAdcock** [comment]
> if the pillar is no longer relevant for special report articles, as it makes pillar and the special report status mutually exclusive. 

I’d check in with design on this. I can imagine an opinion piece that relates to a special report. Would it take normal opinion styling or something different? Today, it probably looks like an opinion piece, but what about in 6 months?

It would also be worth asking whether there’s anything else coming down the pipe, similar to special report. For instance, I can imagine “key moments” like elections getting their own article look and feel, investigations, maybe breaking news.

All of this is kind of Devil’s Advocate speculation to ensure we provide a scalable solution that can handle any interesting and useful new formats that editorial can throw at it!

**Comment by JamieB-gu** [comment]
> anything else coming down the pipe, similar to special report

Yeah, this is the sort of thing that makes me nervous about deciding here that "special report" is definitely a one-off "sixth Pillar".

> I can imagine an opinion piece that relates to a special report. Would it take normal opinion styling or something different? Today, it probably looks like an opinion piece, but what about in 6 months

Good question. AFAIK we also run into this issue with pieces that are `Design.Comment` and `Pillar.News`: they ignore the fact that they're `Pillar.News` and use a `Pillar.Opinion` colour scheme.

**Comment by JamieB-gu** [comment]
Make sure you bump the version to `0.5.0` since this is a breaking change!

**Comment by gtrufitt** [comment]
Ah wow, ok, yeah, this makes sense actually, thanks!

**Pull request merged**
